### ISSUE TITLE
Using the ov5640 camera 

### ISSUE THREAD

**Issue by fabiendostie** [limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera#11]
Hello, hoping someone here will be able to help me!
What should i change in the camera index.h file for it to work properly?
or what needs to be done for the board to work with that camera?
esp32s3 sense
ov5640 camera
arduino ide2.3.2
esp32 v3.02 by espressif 

on the serial monitor I get this when i use the code without modifications.
``
10:44:21.882 -> 
10:44:31.752 -> E (12590) camera: Camera probe failed with error 0x105(ESP_ERR_NOT_FOUND)
10:44:31.752 -> E (12590) gdma: gdma_disconnect(238): no peripheral is connected to the channel
10:44:31.752 -> Camera init failed with error 0x105
``

thanks

**Comment by limengdu** [comment]
The error has nothing to do with the camera model, the code currently does not support esp-arduino 3.0.x and above.

**Comment by fabiendostie** [comment]
I'll try to roll back then. I'll keep you posted.
