### ISSUE TITLE
Error when uploading code

### ISSUE THREAD

**Issue by suitablebat9** [limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera#13]
when i try to upload the code i get this error

C:\Users\suita\Downloads\SeeedStudio-XIAO-ESP32S3-Sense-camera-main\SeeedStudio-XIAO-ESP32S3-Sense-camera-main\CameraWebServer\app_httpd.cpp: In function 'void setupLedFlash(int)':
C:\Users\suita\Downloads\SeeedStudio-XIAO-ESP32S3-Sense-camera-main\SeeedStudio-XIAO-ESP32S3-Sense-camera-main\CameraWebServer\app_httpd.cpp:1389:5: error: 'ledcSetup' was not declared in this scope; did you mean 'ledc_stop'?
 1389 |     ledcSetup(LED_LEDC_CHANNEL, 5000, 8);
      |     ^~~~~~~~~
      |     ledc_stop
C:\Users\suita\Downloads\SeeedStudio-XIAO-ESP32S3-Sense-camera-main\SeeedStudio-XIAO-ESP32S3-Sense-camera-main\CameraWebServer\app_httpd.cpp:1390:5: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
 1390 |     ledcAttachPin(pin, LED_LEDC_CHANNEL);
      |     ^~~~~~~~~~~~~
      |     ledcAttach

exit status 1

Compilation error: 'ledcSetup' was not declared in this scope; did you mean 'ledc_stop'?

**Comment by limengdu** [comment]
If you are using esp-arduino 3.0.x, use the program here: https://github.com/limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera/tree/main/CameraWebServer_for_esp-arduino_3.0.x
