### ISSUE TITLE
Fast forward recoding in sdcard.

### ISSUE THREAD

**Issue by ramendrapathak** [limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera#14]
i am trying to use record video.ino file in which when we play the video the video plays in fastforward way. Can anyone help me with the solution please.
 Code Link: https://github.com/limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera/tree/main/record_video

**Comment by limengdu** [comment]
https://github.com/limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera/tree/main/record_video_decorder/ESP32-CAM_MJPEG2SD

建议你使用这里的程序来录制视频
