### ISSUE TITLE
报错：In function 'void setupLedFlash(int)': 麻烦帮忙看下为啥

### ISSUE THREAD

**Issue by shjjwjy** [limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera#15]
CameraWebServer\app_httpd.cpp: In function 'void setupLedFlash(int)':
CameraWebServer\app_httpd.cpp:1389:5: error: 'ledcSetup' was not declared in this scope; did you mean 'ledc_stop'?
CameraWebServer\app_httpd.cpp:1390:5: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?

**Comment by limengdu** [comment]
If you are using esp-arduino 3.0.x, use the program here: https://github.com/limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera/tree/main/CameraWebServer_for_esp-arduino_3.0.x
