### ISSUE TITLE
Can't open AVI files

### ISSUE THREAD

**Issue by tkyktcy** [limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera#2]
After upload "record_vide.ino" and run it. Some AVI files were created but could not be opened in Windows 11. 
Does someone success to play it?

**Comment by limengdu** [comment]
Since this example does not involve video encoding, the exported video in AVI format is composited from each frame in MJPG format. This may require some specific video players to be able to view the recorded video content.
