### ISSUE TITLE
Continuous Video

### ISSUE THREAD

**Issue by johnmcginn1** [limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera#3]
Hi,

Thank you very much for you code, its working great! Do you know if its possible to record continuous video using the code, similar to a real camera? I know that you can alter the duration of the recording but if there is a way to stop/start recording during a stream or onto an SD card that would be great.

Thank you!

**Comment by limengdu** [comment]
Update the sample programme:

https://github.com/limengdu/SeeedStudio-XIAO-ESP32S3-Sense-camera/tree/main/record_video_decorder/ESP32-CAM_MJPEG2SD
